-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 10:55:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbVideoStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbVideoStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbVideoStore` DEFAULT CHARACTER SET utf8 ;
USE `dbVideoStore` ;

-- -----------------------------------------------------
-- Table `dbVideoStore`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVideoStore`.`Video` (
  `Video_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `production_date` DATE NULL,
  `star_actors` VARCHAR(45) NULL,
  `producer` VARCHAR(45) NULL,
  `director` VARCHAR(45) NULL,
  PRIMARY KEY (`Video_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVideoStore`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVideoStore`.`Customer` (
  `Customer_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVideoStore`.`Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVideoStore`.`Rental` (
  `Rental_id` INT NOT NULL AUTO_INCREMENT,
  `Video_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `checkout_date` DATE NULL,
  `due_date` DATE NULL,
  `checkin_date` DATE NULL,
  `late_status` ENUM('LATE', 'NOT LATE') NULL,
  `rental_fees_accrued` INT(10) NULL,
  PRIMARY KEY (`Rental_id`, `Video_id`, `Customer_id`),
  INDEX `fk_Video_idx` (`Video_id` ASC) VISIBLE,
  INDEX `fk_Customer_idx` (`Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Video`
    FOREIGN KEY (`Video_id`)
    REFERENCES `dbVideoStore`.`Video` (`Video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `dbVideoStore`.`Customer` (`Customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
